"""Floating-point diagnostics for low shell Bessel cross-product roots.

This module is deliberately *not* a certification routine.  It uses ordinary
``mpmath`` multiprecision values, sign-change scans, and floating-point
bisection.  The resulting brackets and counts are diagnostic evidence only and
do not discharge ``COMP-certified-bessel``.

The raw evaluator uses

    F_{ell+1/2,rho}(k)
      = J_{ell+1/2}(rho k) Y_{ell+1/2}(k)
        - Y_{ell+1/2}(rho k) J_{ell+1/2}(k).

The independent stabilized evaluator uses Riccati--spherical functions
``psi_ell(z) = z j_ell(z)`` and ``eta_ell(z) = z y_ell(z)`` generated by their
trigonometric initial values and three-term recurrence.  Its determinant
``R_ell`` has the same roots and satisfies

    F_{ell+1/2,rho}(k) = 2 R_ell(k) / (pi k sqrt(rho)).
"""

from __future__ import annotations

import argparse
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable, Sequence

import mpmath as mp


DEFAULT_RHO = "0.5"
DEFAULT_ELLS = (0, 1, 2)
DEFAULT_K_MIN = "0.000001"
DEFAULT_K_MAX = "20"
DEFAULT_SCAN_STEP = "0.01"
DEFAULT_BRACKET_WIDTH = "1e-20"
DEFAULT_DPS = 80
COMPARISON_POINTS = ("0.25", "1", "3", "7", "11", "17")


@dataclass(frozen=True)
class ApproximateRootBracket:
    """A non-rigorous floating-point sign-change bracket."""

    ell: int
    radial_index: int
    left: mp.mpf
    right: mp.mpf

    @property
    def midpoint(self) -> mp.mpf:
        return (self.left + self.right) / 2

    @property
    def width(self) -> mp.mpf:
        return self.right - self.left


def raw_bessel_cross_product(ell: int, rho: mp.mpf, k: mp.mpf) -> mp.mpf:
    """Evaluate the defining ordinary-Bessel cross-product directly."""

    _validate_inputs(ell, rho, k)
    nu = mp.mpf(ell) + mp.mpf("0.5")
    inner = rho * k
    return (
        mp.besselj(nu, inner) * mp.bessely(nu, k)
        - mp.bessely(nu, inner) * mp.besselj(nu, k)
    )


def riccati_spherical_pair(ell: int, z: mp.mpf) -> tuple[mp.mpf, mp.mpf]:
    """Return ``(z*j_ell(z), z*y_ell(z))`` via trigonometric recurrence."""

    if ell < 0:
        raise ValueError("ell must be nonnegative")
    if z <= 0:
        raise ValueError("z must be positive")

    psi_previous = mp.sin(z)
    eta_previous = -mp.cos(z)
    if ell == 0:
        return psi_previous, eta_previous

    psi_current = mp.sin(z) / z - mp.cos(z)
    eta_current = -mp.cos(z) / z - mp.sin(z)
    if ell == 1:
        return psi_current, eta_current

    for order in range(1, ell):
        coefficient = mp.mpf(2 * order + 1) / z
        psi_next = coefficient * psi_current - psi_previous
        eta_next = coefficient * eta_current - eta_previous
        psi_previous, psi_current = psi_current, psi_next
        eta_previous, eta_current = eta_current, eta_next
    return psi_current, eta_current


def stabilized_riccati_cross_product(ell: int, rho: mp.mpf, k: mp.mpf) -> mp.mpf:
    """Evaluate the root-equivalent Riccati--spherical determinant."""

    _validate_inputs(ell, rho, k)
    inner_psi, inner_eta = riccati_spherical_pair(ell, rho * k)
    outer_psi, outer_eta = riccati_spherical_pair(ell, k)
    return inner_psi * outer_eta - outer_psi * inner_eta


def stabilized_cross_product_as_raw(ell: int, rho: mp.mpf, k: mp.mpf) -> mp.mpf:
    """Rescale the stabilized determinant to the raw ``F`` normalization."""

    determinant = stabilized_riccati_cross_product(ell, rho, k)
    return 2 * determinant / (mp.pi * k * mp.sqrt(rho))


def scaled_discrepancy(left: mp.mpf, right: mp.mpf) -> mp.mpf:
    """Return an absolute discrepancy scaled by the larger evaluator size."""

    return abs(left - right) / max(mp.mpf(1), abs(left), abs(right))


def small_k_leading_coefficient(ell: int, rho: mp.mpf) -> mp.mpf:
    """Return the formal coefficient of ``k`` in the small-``k`` determinant.

    The Riccati recurrence gives the diagnostic expansion

        R_ell(k) = [(rho**(-ell) - rho**(ell+1)) / (2*ell+1)] k + O(k**3).

    No remainder bound is supplied here, so this is a symbolic sanity check and
    not a proof that the omitted interval next to ``k=0`` is root-free.
    """

    if ell < 0:
        raise ValueError("ell must be nonnegative")
    if not (0 < rho < 1):
        raise ValueError("rho must satisfy 0 < rho < 1")
    return (rho ** (-ell) - rho ** (ell + 1)) / (2 * ell + 1)


def approximate_root_brackets(
    ell: int,
    rho: mp.mpf | str = DEFAULT_RHO,
    k_min: mp.mpf | str = DEFAULT_K_MIN,
    k_max: mp.mpf | str = DEFAULT_K_MAX,
    scan_step: mp.mpf | str = DEFAULT_SCAN_STEP,
    target_width: mp.mpf | str = DEFAULT_BRACKET_WIDTH,
) -> list[ApproximateRootBracket]:
    """Locate sign changes and bisect them using non-rigorous arithmetic.

    This procedure makes no claim that the fixed scan finds every zero.  It is
    suitable only for reproducible exploratory diagnostics and regression tests.
    """

    rho = mp.mpf(rho)
    k_min = mp.mpf(k_min)
    k_max = mp.mpf(k_max)
    scan_step = mp.mpf(scan_step)
    target_width = mp.mpf(target_width)

    if not (mp.mpf(0) < k_min < k_max):
        raise ValueError("require 0 < k_min < k_max")
    if scan_step <= 0:
        raise ValueError("scan_step must be positive")
    if target_width <= 0:
        raise ValueError("target_width must be positive")

    left = mp.mpf(k_min)
    left_value = stabilized_riccati_cross_product(ell, rho, left)
    sign_change_intervals: list[tuple[mp.mpf, mp.mpf]] = []

    while left < k_max:
        right = min(left + scan_step, k_max)
        right_value = stabilized_riccati_cross_product(ell, rho, right)
        if left_value == 0:
            sign_change_intervals.append((left, left))
        elif right_value == 0 or left_value * right_value < 0:
            sign_change_intervals.append((left, right))
        left, left_value = right, right_value

    brackets: list[ApproximateRootBracket] = []
    for candidate_left, candidate_right in sign_change_intervals:
        bisected_left, bisected_right = _floating_point_bisect(
            ell,
            rho,
            candidate_left,
            candidate_right,
            target_width,
        )
        midpoint = (bisected_left + bisected_right) / 2
        if brackets and abs(midpoint - brackets[-1].midpoint) <= scan_step:
            continue
        brackets.append(
            ApproximateRootBracket(
                ell=ell,
                radial_index=len(brackets) + 1,
                left=bisected_left,
                right=bisected_right,
            )
        )
    return brackets


def weighted_count(brackets_by_ell: dict[int, Sequence[ApproximateRootBracket]]) -> int:
    """Apply the dimension-three angular multiplicity ``2*ell+1``."""

    return sum((2 * ell + 1) * len(brackets) for ell, brackets in brackets_by_ell.items())


def build_report(
    rho: mp.mpf | str = DEFAULT_RHO,
    ells: Iterable[int] = DEFAULT_ELLS,
    k_min: mp.mpf | str = DEFAULT_K_MIN,
    k_max: mp.mpf | str = DEFAULT_K_MAX,
    scan_step: mp.mpf | str = DEFAULT_SCAN_STEP,
    target_width: mp.mpf | str = DEFAULT_BRACKET_WIDTH,
    dps: int = DEFAULT_DPS,
) -> str:
    """Build the deterministic Markdown diagnostic report."""

    ell_values = tuple(ells)
    with mp.workdps(dps):
        rho_value = mp.mpf(rho)
        k_min_value = mp.mpf(k_min)
        k_max_value = mp.mpf(k_max)
        step_value = mp.mpf(scan_step)
        width_value = mp.mpf(target_width)
        brackets_by_ell = {
            ell: approximate_root_brackets(
                ell,
                rho_value,
                k_min_value,
                k_max_value,
                step_value,
                width_value,
            )
            for ell in ell_values
        }

        lines = [
            "# Bessel cross-product finite-window diagnostic",
            "",
            "> **FLOATING-POINT DIAGNOSTIC — NOT CERTIFIED.** This report does not discharge",
            "> `COMP-certified-bessel` or any proof obligation.",
            "",
            "## Deterministic reproduction",
            "",
            "```powershell",
            "python -m pip install -r computations/requirements-diagnostic.txt",
            "python computations/bessel_cross_product_diagnostic.py --output computations/results/bessel_cross_product_rho_half.md",
            "python -m unittest discover -s computations/tests -p \"test_*.py\"",
            "```",
            "",
            f"- Arithmetic: `mpmath {mp.__version__}` multiprecision floating point at `{dps}` decimal digits.",
            f"- Target window: `rho={_plain(rho_value)}`, `ell={','.join(map(str, ell_values))}`, "
            f"`0 < k < {_plain(k_max_value)}`; numerical scan starts at `k={_plain(k_min_value)}`.",
            f"- Scan step: `{_plain(step_value)}`; bisection target width: `{_scientific(width_value, 3)}`.",
            "- Evaluator A: raw ordinary-Bessel cross-product.",
            "- Evaluator B: Riccati–spherical trigonometric recurrence, rescaled to the raw normalization.",
            "",
            "## Evaluator comparison",
            "",
            "With `psi_ell(z)=z j_ell(z)` and `eta_ell(z)=z y_ell(z)`, the stabilized "
            "determinant is `R_ell(k)=psi_ell(rho k) eta_ell(k)-psi_ell(k) eta_ell(rho k)`, "
            "and `F_(ell+1/2,rho)(k)=2 R_ell(k)/(pi k sqrt(rho))`.",
            "",
            "The discrepancy is `|raw-stabilized| / max(1,|raw|,|stabilized|)`.",
            "",
            "| ell | k | raw Bessel F | stabilized-as-raw F | scaled discrepancy |",
            "| ---: | ---: | ---: | ---: | ---: |",
        ]

        for ell in ell_values:
            for k_text in COMPARISON_POINTS:
                k = mp.mpf(k_text)
                raw = raw_bessel_cross_product(ell, rho_value, k)
                stabilized = stabilized_cross_product_as_raw(ell, rho_value, k)
                discrepancy = scaled_discrepancy(raw, stabilized)
                lines.append(
                    f"| {ell} | {_plain(k)} | {_scientific(raw, 12)} | "
                    f"{_scientific(stabilized, 12)} | {_scientific(discrepancy, 4)} |"
                )

        lines.extend(
            [
                "",
                "## Small-k symbolic sanity check",
                "",
                "The recurrence gives the formal expansion "
                "`R_ell(k) = c_ell(rho) k + O(k^3)`, where "
                "`c_ell(rho) = (rho^(-ell)-rho^(ell+1))/(2 ell+1)`.",
                "The positive coefficients below are consistent with no near-zero sign change, but the "
                "unbounded remainder means this does not verify the unscanned interval.",
                "",
                "| ell | c_ell(1/2) | sign |",
                "| ---: | ---: | :---: |",
            ]
        )
        for ell in ell_values:
            coefficient = small_k_leading_coefficient(ell, rho_value)
            lines.append(f"| {ell} | {_plain(coefficient)} | {'positive' if coefficient > 0 else 'nonpositive'} |")

        lines.extend(
            [
                "",
                "## Approximate sign-change brackets",
                "",
                "Each row is a floating-point sign-change/bisection result, not an interval enclosure.",
                "",
                "| ell | radial index | approximate left | approximate right | midpoint | |R(midpoint)| |",
                "| ---: | ---: | ---: | ---: | ---: | ---: |",
            ]
        )
        for ell in ell_values:
            for bracket in brackets_by_ell[ell]:
                residual = abs(stabilized_riccati_cross_product(ell, rho_value, bracket.midpoint))
                lines.append(
                    f"| {ell} | {bracket.radial_index} | {_fixed(bracket.left, 22)} | "
                    f"{_fixed(bracket.right, 22)} | {_fixed(bracket.midpoint, 16)} | "
                    f"{_scientific(residual, 4)} |"
                )

        lines.extend(
            [
                "",
                "## Counting summary",
                "",
                "| ell | approximate radial root count | angular multiplicity 2 ell + 1 | weighted contribution |",
                "| ---: | ---: | ---: | ---: |",
            ]
        )
        for ell in ell_values:
            count = len(brackets_by_ell[ell])
            multiplicity = 2 * ell + 1
            lines.append(f"| {ell} | {count} | {multiplicity} | {count * multiplicity} |")
        total_unweighted = sum(len(brackets) for brackets in brackets_by_ell.values())
        total_weighted = weighted_count(brackets_by_ell)
        lines.extend(
            [
                f"| **total** | **{total_unweighted}** | — | **{total_weighted}** |",
                "",
                f"Diagnostic conclusion: the fixed-grid scan finds `{total_unweighted}` radial roots and a "
                f"dimension-three multiplicity-weighted count of `{total_weighted}` for the selected "
                f"`ell` values below `k={_plain(k_max_value)}` (equivalently below `Lambda={_plain(k_max_value**2)}`).",
                "",
                "## Limitations",
                "",
                "- `mpmath` values are multiprecision floating-point approximations, not interval or ball values.",
                "- Printed brackets are not outward-rounded and therefore are not rigorous enclosures.",
                "- A fixed sign-change grid does not prove that every zero was found or that no even-multiplicity zero was missed.",
                f"- The numerical scan omits `0 < k < {_plain(k_min_value)}`; the displayed formal small-`k` term has no controlled remainder.",
                "- The recurrence and raw evaluator agreement is a diagnostic cross-check, not an independence proof.",
                "- Here, `stabilized` means amplitude-rescaled; numerical stability of upward recurrence is not established beyond these low orders and this window.",
                "- Only `rho=1/2`, `ell=0,1,2`, and the finite window `0<k<20` are explored.",
                "- Certification still requires validated special-function evaluation, rigorous root isolation, domain coverage, and reproducible interval/ball arithmetic.",
                "",
            ]
        )
        return "\n".join(lines)


def _floating_point_bisect(
    ell: int,
    rho: mp.mpf,
    left: mp.mpf,
    right: mp.mpf,
    target_width: mp.mpf,
) -> tuple[mp.mpf, mp.mpf]:
    if left == right:
        return left, right
    left_value = stabilized_riccati_cross_product(ell, rho, left)
    right_value = stabilized_riccati_cross_product(ell, rho, right)
    if left_value * right_value > 0:
        raise ValueError("bisection endpoints do not have opposite signs")

    while right - left > target_width:
        midpoint = (left + right) / 2
        midpoint_value = stabilized_riccati_cross_product(ell, rho, midpoint)
        if midpoint_value == 0:
            return midpoint, midpoint
        if left_value * midpoint_value < 0:
            right, right_value = midpoint, midpoint_value
        else:
            left, left_value = midpoint, midpoint_value
    return left, right


def _validate_inputs(ell: int, rho: mp.mpf, k: mp.mpf) -> None:
    if ell < 0:
        raise ValueError("ell must be nonnegative")
    if not (0 < rho < 1):
        raise ValueError("rho must satisfy 0 < rho < 1")
    if k <= 0:
        raise ValueError("k must be positive")


def _plain(value: mp.mpf) -> str:
    return mp.nstr(value, 30)


def _fixed(value: mp.mpf, digits_after_decimal: int) -> str:
    return f"{mp.mpf(value):.{digits_after_decimal}f}"


def _scientific(value: mp.mpf, significant_digits: int) -> str:
    return mp.nstr(value, significant_digits, min_fixed=0, max_fixed=0)


def parse_args(argv: Sequence[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--output",
        type=Path,
        help="write Markdown to this path instead of standard output",
    )
    parser.add_argument("--dps", type=int, default=DEFAULT_DPS)
    parser.add_argument("--scan-step", default=str(DEFAULT_SCAN_STEP))
    parser.add_argument("--bracket-width", default=str(DEFAULT_BRACKET_WIDTH))
    return parser.parse_args(argv)


def main(argv: Sequence[str] | None = None) -> int:
    args = parse_args(argv)
    report = build_report(
        dps=args.dps,
        scan_step=args.scan_step,
        target_width=args.bracket_width,
    )
    if args.output:
        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_text(report, encoding="utf-8", newline="\n")
        print(f"Wrote non-certified floating-point diagnostic: {args.output}")
    else:
        print(report)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
